user_list:
  path: /
  defaults: { _controller: AppBundle:User:list }
  methods: [GET]

user_read:
  path: /{id}
  defaults: { _controller: AppBundle:User:read }
  methods: [GET]

user_create:
  path: /create
  defaults: { _controller: AppBundle:User:create }
  methods: [POST]
